/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.drive;
import java.awt.Color;
import java.awt.Container;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.TreePath;


/**
 *
 * @author Mauricio
 */
public class controlFrame extends javax.swing.JFrame {
    public String x = "not selected";
    /**
     * Creates new form controlFrame
     */
    public controlFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        remoteFilesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uploadFilePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        uploadDirPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        downloadFilePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        downloadDirPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        deleteFilePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deleteDirPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        localFilesPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        OnlineB = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FilesView = new javax.swing.JScrollPane();
        Tree1 = new javax.swing.JTree();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setName("background"); // NOI18N
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(102, 102, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 40));

        remoteFilesPanel.setBackground(new java.awt.Color(102, 102, 255));
        remoteFilesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remoteFilesPanel.setPreferredSize(new java.awt.Dimension(200, 50));
        remoteFilesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remoteFilesPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                remoteFilesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remoteFilesPanelMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Archivos remotos");

        javax.swing.GroupLayout remoteFilesPanelLayout = new javax.swing.GroupLayout(remoteFilesPanel);
        remoteFilesPanel.setLayout(remoteFilesPanelLayout);
        remoteFilesPanelLayout.setHorizontalGroup(
            remoteFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remoteFilesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        remoteFilesPanelLayout.setVerticalGroup(
            remoteFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remoteFilesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(remoteFilesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 40));

        uploadFilePanel.setBackground(new java.awt.Color(102, 102, 255));
        uploadFilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadFilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadFilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uploadFilePanelMouseExited(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subir archivo");

        javax.swing.GroupLayout uploadFilePanelLayout = new javax.swing.GroupLayout(uploadFilePanel);
        uploadFilePanel.setLayout(uploadFilePanelLayout);
        uploadFilePanelLayout.setHorizontalGroup(
            uploadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        uploadFilePanelLayout.setVerticalGroup(
            uploadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(uploadFilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 40));

        uploadDirPanel.setBackground(new java.awt.Color(102, 102, 255));
        uploadDirPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadDirPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadDirPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uploadDirPanelMouseExited(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subir carpeta");

        javax.swing.GroupLayout uploadDirPanelLayout = new javax.swing.GroupLayout(uploadDirPanel);
        uploadDirPanel.setLayout(uploadDirPanelLayout);
        uploadDirPanelLayout.setHorizontalGroup(
            uploadDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        uploadDirPanelLayout.setVerticalGroup(
            uploadDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(uploadDirPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        downloadFilePanel.setBackground(new java.awt.Color(102, 102, 255));
        downloadFilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downloadFilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                downloadFilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downloadFilePanelMouseExited(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descargar archivo");

        javax.swing.GroupLayout downloadFilePanelLayout = new javax.swing.GroupLayout(downloadFilePanel);
        downloadFilePanel.setLayout(downloadFilePanelLayout);
        downloadFilePanelLayout.setHorizontalGroup(
            downloadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        downloadFilePanelLayout.setVerticalGroup(
            downloadFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(downloadFilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 40));

        downloadDirPanel.setBackground(new java.awt.Color(102, 102, 255));
        downloadDirPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downloadDirPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                downloadDirPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downloadDirPanelMouseExited(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descargar carpeta");

        javax.swing.GroupLayout downloadDirPanelLayout = new javax.swing.GroupLayout(downloadDirPanel);
        downloadDirPanel.setLayout(downloadDirPanelLayout);
        downloadDirPanelLayout.setHorizontalGroup(
            downloadDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        downloadDirPanelLayout.setVerticalGroup(
            downloadDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(downloadDirPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 40));

        deleteFilePanel.setBackground(new java.awt.Color(102, 102, 255));
        deleteFilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteFilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteFilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteFilePanelMouseExited(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar archivo");

        javax.swing.GroupLayout deleteFilePanelLayout = new javax.swing.GroupLayout(deleteFilePanel);
        deleteFilePanel.setLayout(deleteFilePanelLayout);
        deleteFilePanelLayout.setHorizontalGroup(
            deleteFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        deleteFilePanelLayout.setVerticalGroup(
            deleteFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(deleteFilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 40));

        deleteDirPanel.setBackground(new java.awt.Color(102, 102, 255));
        deleteDirPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteDirPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteDirPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteDirPanelMouseExited(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eliminar carpeta");

        javax.swing.GroupLayout deleteDirPanelLayout = new javax.swing.GroupLayout(deleteDirPanel);
        deleteDirPanel.setLayout(deleteDirPanelLayout);
        deleteDirPanelLayout.setHorizontalGroup(
            deleteDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        deleteDirPanelLayout.setVerticalGroup(
            deleteDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(deleteDirPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 160, 40));

        localFilesPanel2.setBackground(new java.awt.Color(102, 102, 255));
        localFilesPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        localFilesPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localFilesPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                localFilesPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                localFilesPanel2MouseExited(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Archivos Locales");

        javax.swing.GroupLayout localFilesPanel2Layout = new javax.swing.GroupLayout(localFilesPanel2);
        localFilesPanel2.setLayout(localFilesPanel2Layout);
        localFilesPanel2Layout.setHorizontalGroup(
            localFilesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localFilesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        localFilesPanel2Layout.setVerticalGroup(
            localFilesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localFilesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(localFilesPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        OnlineB.setText("Online");
        OnlineB.setToolTipText("");
        OnlineB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnlineBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnlineBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnlineBMouseExited(evt);
            }
        });
        jPanel1.add(OnlineB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Sistema de Almacenamiento");

        FilesView.setForeground(new java.awt.Color(240, 240, 240));

        Tree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                Tree1ValueChanged(evt);
            }
        });
        FilesView.setViewportView(Tree1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel2)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilesView)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilesView, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 520, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remoteFilesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remoteFilesPanelMouseEntered
        remoteFilesPanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_remoteFilesPanelMouseEntered

    private void remoteFilesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remoteFilesPanelMouseExited
        remoteFilesPanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_remoteFilesPanelMouseExited

    private void uploadFilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadFilePanelMouseEntered
        uploadFilePanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_uploadFilePanelMouseEntered

    private void uploadFilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadFilePanelMouseExited
        uploadFilePanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_uploadFilePanelMouseExited

    private void uploadDirPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadDirPanelMouseEntered
        uploadDirPanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_uploadDirPanelMouseEntered

    private void uploadDirPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadDirPanelMouseExited
        uploadDirPanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_uploadDirPanelMouseExited

    private void downloadFilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadFilePanelMouseEntered
        downloadFilePanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_downloadFilePanelMouseEntered

    private void downloadFilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadFilePanelMouseExited
        downloadFilePanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_downloadFilePanelMouseExited

    private void downloadDirPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadDirPanelMouseEntered
        downloadDirPanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_downloadDirPanelMouseEntered

    private void downloadDirPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadDirPanelMouseExited
        downloadDirPanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_downloadDirPanelMouseExited

    private void deleteFilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteFilePanelMouseEntered
        deleteFilePanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_deleteFilePanelMouseEntered

    private void deleteFilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteFilePanelMouseExited
        deleteFilePanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_deleteFilePanelMouseExited

    private void deleteDirPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDirPanelMouseEntered
        deleteDirPanel.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_deleteDirPanelMouseEntered

    private void deleteDirPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDirPanelMouseExited
        deleteDirPanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_deleteDirPanelMouseExited

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_HomeMouseExited

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        FilesView.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void remoteFilesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remoteFilesPanelMouseClicked
        // TODO add your handling code here:
        FilesView.setVisible(true);
       // String Udir = "C:\\Users\\reyma\\Desktop\\ALBERTO";//Dirección se debe cambiar a la se usuario
//        UserCloud obj = new UserCloud();
//        JTree obj2 = new JTree (obj.MyFiles(Udir));
//        Tree1.setModel(obj2.getModel());
        System.out.println("remote");
        //CONEXION
        try {
            int pto = 1025;
            Socket cl = new Socket("localhost", pto);
            System.out.println("Conexion con servidor exitosa.. preparado para recibir objeto..");
            
            //INICIO DE CONFIGURACIÓN PARA RECIBIR OBJETO
            ObjectOutputStream oos = new ObjectOutputStream(cl.getOutputStream());
            ObjectInputStream ois = new ObjectInputStream(cl.getInputStream());
            //Recepcion de objeto
            Objeto ob2 = (Objeto) ois.readObject();
            System.out.println("Objeto recibido desde " + cl.getInetAddress() + ":" + cl.getPort() + " con los datos:");
            System.out.println("Flag:" + ob2.getX());
            JTree arbol = new JTree(ob2.getTree());
            Tree1.setModel(arbol.getModel());
            //Envio de datos de confirmación
            Objeto ob = new Objeto(0,ob2.getTree());
            System.out.println("Enviando objeto con Flag: " + ob.getX());
            oos.writeObject(ob);
            oos.flush();
            System.out.println("Objeto enviado..");
            ois.close();
            oos.close();
            cl.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_remoteFilesPanelMouseClicked

    private void localFilesPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localFilesPanel2MouseClicked
        // TODO add your handling code here:
        FilesView.setVisible(true);
        String Udir = "C:\\Users\\reyma\\Desktop\\MARCO";//Dirección se debe cambiar a la se usuario
        UserCloud obj = new UserCloud();
        JTree obj2 = new JTree (obj.MyFiles(Udir));
        Tree1.setModel(obj2.getModel());
        System.out.println("local");
    }//GEN-LAST:event_localFilesPanel2MouseClicked

    private void localFilesPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localFilesPanel2MouseEntered
        // TODO add your handling code here:
         localFilesPanel2.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_localFilesPanel2MouseEntered

    private void localFilesPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localFilesPanel2MouseExited
        // TODO add your handling code here:
        localFilesPanel2.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_localFilesPanel2MouseExited

    private void OnlineBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnlineBMouseEntered
        // TODO add your handling code here:
        //OnlineB.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_OnlineBMouseEntered

    private void OnlineBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnlineBMouseExited
        // TODO add your handling code here:
        //OnlineB.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_OnlineBMouseExited

    private void OnlineBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnlineBMouseClicked
        // TODO add your handling code here:
        OnlineB.setBackground(new Color(0,255,0));
        System.out.println(x);
    }//GEN-LAST:event_OnlineBMouseClicked

    private void Tree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_Tree1ValueChanged
        // TODO add your handling code here:
      x =  Tree1.getSelectionPath().getLastPathComponent().toString();
      System.out.println(x);
      
    }//GEN-LAST:event_Tree1ValueChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane FilesView;
    private javax.swing.JPanel Home;
    private javax.swing.JToggleButton OnlineB;
    private javax.swing.JTree Tree1;
    private javax.swing.JPanel background;
    private javax.swing.JPanel deleteDirPanel;
    private javax.swing.JPanel deleteFilePanel;
    private javax.swing.JPanel downloadDirPanel;
    private javax.swing.JPanel downloadFilePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel localFilesPanel2;
    private javax.swing.JPanel remoteFilesPanel;
    private javax.swing.JPanel uploadDirPanel;
    private javax.swing.JPanel uploadFilePanel;
    // End of variables declaration//GEN-END:variables
}
